this={}
TppSoldier2.ReloadSoldier2ParameterTables{
  sightFormParameter={
    contactSightForm={distance=2,verticalAngle=160,horizontalAngle=130},
    normalSightForm={distance=88,verticalAngle=60,horizontalAngle=100},
    farSightForm={distance=133,verticalAngle=30,horizontalAngle=30},
    searchLightSightForm={distance=77,verticalAngle=15,horizontalAngle=15},
    observeSightForm={distance=201,verticalAngle=5,horizontalAngle=5},
    baseSight={
      discovery={distance=15,verticalAngle=36,horizontalAngle=48},
      indis={distance=33,verticalAngle=60,horizontalAngle=80},
      dim={distance=66,verticalAngle=60,horizontalAngle=80},
      far={distance=104,verticalAngle=12,horizontalAngle=8}
    },
    nightSight={
      discovery={distance=14,verticalAngle=30,horizontalAngle=40},
      indis={distance=26,verticalAngle=60,horizontalAngle=60},
      dim={distance=62,verticalAngle=60,horizontalAngle=60},
      far={distance=0,verticalAngle=0,horizontalAngle=0}
    },
    combatSight={
      discovery={distance=17,verticalAngle=36,horizontalAngle=60},
      indis={distance=44,verticalAngle=60,horizontalAngle=100},
      dim={distance=77,verticalAngle=60,horizontalAngle=100},
      far={distance=106,verticalAngle=30,horizontalAngle=30}
    },
    walkerGearSight={
      discovery={distance=18,verticalAngle=36,horizontalAngle=60},
      indis={distance=38,verticalAngle=60,horizontalAngle=100},
      dim={distance=78,verticalAngle=60,horizontalAngle=100},
      far={distance=124,verticalAngle=30,horizontalAngle=30}
    },
    observeSight={
      discovery={distance=16,verticalAngle=36,horizontalAngle=48},
      indis={distance=102,verticalAngle=12,horizontalAngle=8},
      dim={distance=73,verticalAngle=5,horizontalAngle=5},
      far={distance=111,verticalAngle=5,horizontalAngle=5},
      observe={distance=202,verticalAngle=5,horizontalAngle=5}
    },
    snipingSight={
      discovery={distance=19,verticalAngle=36,horizontalAngle=48},
      indis={distance=106,verticalAngle=12,horizontalAngle=8},
      dim={distance=67,verticalAngle=5,horizontalAngle=5},
      far={distance=103,verticalAngle=5,horizontalAngle=5},
      observe={distance=203,verticalAngle=5,horizontalAngle=5}
    },
    searchLightSight={
      discovery={distance=46,verticalAngle=8,horizontalAngle=8},
      indis={distance=0,verticalAngle=0,horizontalAngle=0},
      dim={distance=77,verticalAngle=12,horizontalAngle=12},
      far={distance=0,verticalAngle=0,horizontalAngle=0}
    },
    armoredVehicleSight={
      discovery={distance=24,verticalAngle=36,horizontalAngle=60},
      indis={distance=37,verticalAngle=60,horizontalAngle=100},
      dim={distance=76,verticalAngle=60,horizontalAngle=100},
      far={distance=122,verticalAngle=30,horizontalAngle=30},
      observe={distance=121,verticalAngle=5,horizontalAngle=5}
    },
    zombieSight={
      discovery={distance=11,verticalAngle=36,horizontalAngle=48},
      indis={distance=19,verticalAngle=60,horizontalAngle=80},
      dim={distance=47,verticalAngle=60,horizontalAngle=80},
      far={distance=0,verticalAngle=12,horizontalAngle=8}
    },
    msfSight={
      discovery={distance=15,verticalAngle=36,horizontalAngle=48},
      indis={distance=33,verticalAngle=60,horizontalAngle=80},
      dim={distance=66,verticalAngle=60,horizontalAngle=80},
      far={distance=99,verticalAngle=12,horizontalAngle=8}
    },
    vehicleSight={
      discovery={distance=22,verticalAngle=36,horizontalAngle=48},
      indis={distance=42,verticalAngle=60,horizontalAngle=80},
      dim={distance=52,verticalAngle=60,horizontalAngle=80},
      far={distance=92,verticalAngle=12,horizontalAngle=8}
    },
    sandstormSight={distanceRate=.4,angleRate=.5},
    rainSight={distanceRate=.6,angleRate=.8},
    cloudySight={distanceRate=.9,angleRate=1},
    foggySight={distanceRate=.5,angleRate=.6}
  },
  sightCamouflageParameter={
    discovery={enemy=530,character=530,object=530},
    indis={enemy=80,character=210,object=270},
    dim={enemy=-50,character=30,object=130},
    far={enemy=-310,character=0,object=70},
    bushDensityThresold=100
  },
  hearingRangeParameter={
    normal={zero=2,ss=4.5,hs=7.5,s=9,m=15,l=45,hll=69,ll=240,alert=160,special=500},
    sandstorm={zero=0.5,ss=1,hs=1.5,s=4.5,m=5,l=22,hll=33,ll=44,alert=66,special=500},
    rain={zero=1.5,ss=3,hs=4.5,s=8,m=12,l=33,hll=57,ll=160,alert=160,special=500}
  },
  lifeParameterTable={maxLife=5200,maxStamina=3e3,maxLimbLife=3000,maxArmorLife=9999,maxHelmetLife=1000,sleepRecoverSec=150,faintRecoverSec=33,dyingSec=57},
  zombieParameterTable={highHeroicValue=1e3}
}
return this
