SoundTppAnimal={
  SetupSwitch=function()
    SoundAnimalAnimEvent.SetupAnimalRattleSuit{
      reference={"RATTLE_SUIT"},
      event="sfx_m_Anml_Rtl_Suit",
      group_suit="anml_suit_switch",
      group_class="anml_type_switch",
      action={"Tr","Cn","Gp"},
      class={"hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_vol","dog","ber","bor","loc","ppy","dog","dog","dog","dog","dog","dog","dog","dog","dog"}
    }
    SoundAnimalAnimEvent.SetupAnimalFootStep{
      reference={"FOOT_GROUND_L","FOOT_GROUND_R","FOOT_LEAVE_L","FOOT_LEAVE_R","ARM_GROUND_L","ARM_GROUND_R","ARM_LEAVE_L","ARM_LEAVE_R"},
      events={"sfx_m_Anml_Foot_Grd_L","sfx_m_Anml_Foot_Grd_R","sfx_m_Anml_Foot_Lev_L","sfx_m_Anml_Foot_Lev_R","sfx_m_Anml_Arm_Grd_L","sfx_m_Anml_Arm_Grd_R","sfx_m_Anml_Arm_Lev_L","sfx_m_Anml_Arm_Lev_R"},
      group_foot="anml_foot_switch",
      group_class="anml_type_switch",
      action={"Tr","Tr","Tr","Tr","Tr","Tr","Cn","Cn","Cn","Cn","Cn","Cn","Cn","Cn","Gp","Gp","Gp","Gp","Gp","Gp","Gp","Gp","Gp","Gp"},
      frontRear={"F","R"},
      side={"L","R"},
      wet="W",
      class={"hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_sdl","hrs_vol","dog","ber","bor","loc","ppy","dog","dog","dog","dog","dog","dog","dog","dog","dog"},
      type={"soil","rock","grass","grav","wood","iron"},
      soil={symbol="SOILA",wet=true,material={"MTR_SOIL_A","MTR_SOIL_B","MTR_SOIL_C","MTR_SOIL_F","MTR_SOIL_G","MTR_SOIL_H","MTR_SAND_A","MTR_SAND_B"}},
      rock={symbol="ROCKA",wet=true,material={"MTR_ROCK_A","MTR_ROCK_B","MTR_BRIC_A","MTR_CLOT_C","MTR_CONC_A","MTR_CONC_B","MTR_PAPE_A","MTR_RUBB_A","MTR_TILE_A","MTR_VINL_A","MTR_GLAS_A"}},
      grass={symbol="GRASA",wet=true,material={"MTR_TURF_A","MTR_LEAF"}},
      grav={symbol="GRAVA",wet=true,material={"MTR_GRAV_A"}},
      wood={symbol="WOODA",wet=true,material={"MTR_PAPE_B","MTR_PLAS_A","MTR_PLAS_B","MTR_WOOD_A","MTR_WOOD_B","MTR_WOOD_C","MTR_WOOD_D"}},
      iron={symbol="IRONA",wet=true,material={"MTR_IRON_A","MTR_IRON_B","MTR_FENC_A","MTR_FENC_B","MTR_PIPE_A","MTR_PIPE_B","MTR_TIN_A"}}
    }
  end
}
