SoundTppSoldier={
  SetupSwitch=function()
    SoundSoldierAnimEvent.SetupSoldierType{
      group="soldier_type_switch",
      type={"nom","hvy","ish","wmu","qui","vol","nom","nom","nom","hyu","wsp","liq","mgm","nom","mgs","boy","bon","nom","nom","nom","nom","wms","wmh","prs","zom","res5"}
    }
    SoundSoldierAnimEvent.SetupSoldierRattleSuit{
      reference={"RATTLE_SUIT"},event="sfx_E_Rtl_Suit",group="soldier_suit_switch",action={"wk","wkc","rn","rnc","dh","cr","cp"}
    }
    SoundSoldierAnimEvent.SetupSoldierBodyCollision{
      reference={"CHEST_GROUND"},
      event="sfx_E_Chest_Grd",
      group="soldier_chest_switch",
      action={"hitfenc","hitwall"},
      wet="W",
      type={"soil","soilm","rock","clot","grass","grav","wood","iron","fence"},
      soil={symbol="SOILA",wet=false,material={"MTR_SOIL_A","MTR_SOIL_B","MTR_SOIL_E","MTR_SOIL_F","MTR_SOIL_G","MTR_SOIL_H","MTR_SAND_A","MTR_SAND_B","MTR_PLNT_A"}},
      soilm={symbol="ROCKAW",wet=false,material={"MTR_SOIL_D","MTR_WATE_B","MTR_BLOD_A"}},
      rock={symbol="ROCKA",wet=true,material={"MTR_ROCK_A","MTR_ROCK_B","MTR_BRIC_A","MTR_CONC_A","MTR_CONC_B","MTR_PAPE_A","MTR_RUBB_A","MTR_TILE_A","MTR_VINL_A","MTR_GLAS_A","MTR_RUBB_B","MTR_ROCK_P","MTR_BRIR_A"}},
      clot={symbol="CLOTA",wet=false,material={"MTR_CLOT_C","MTR_CLOT_D"}},
      grass={symbol="GRASA",wet=false,material={"MTR_TURF_A","MTR_LEAF","MTR_TLEF"}},grav={symbol="GRAVA",wet=false,material={"MTR_GRAV_A","MTR_SOIL_C"}},
      wood={symbol="WOODA",wet=false,material={"MTR_PAPE_B","MTR_PLAS_A","MTR_PLAS_B","MTR_WOOD_A","MTR_WOOD_B","MTR_WOOD_C","MTR_WOOD_D","MTR_WOOD_W"}},iron={symbol="IRONA",wet=false,material={"MTR_IRON_A","MTR_IRON_B","MTR_FENC_A","MTR_PIPE_A","MTR_PIPE_B","MTR_TIN_A","MTR_IRON_E","MTR_IRON_G"}},
      fence={symbol="FENCA",wet=true,material={"MTR_FENC_B","MTR_CLOT_E","MTR_FENC_F"}}
    }
    SoundSoldierAnimEvent.SetupSoldierFootStep{
      reference={"FOOT_GROUND_L","FOOT_GROUND_R","FOOT_LEAVE_L","FOOT_LEAVE_R"},
      events={"sfx_E_Fs_Grd_L","sfx_E_Fs_Grd_R","sfx_E_Fs_Lev_L","sfx_E_Fs_Lev_R"},
      group="soldier_foot_switch",action={"Wk","Wk","Wk","Wk","Wk","Wk","Wk","Wk","WkC","WkC","WkC","WkC","WkC","WkC","WkC","WkC","Rn","Rn","Wk","Wk","Rn","Rn","Rn","Rn","RnC","RnC","WkC","WkC","RnC","RnC","RnC","RnC","Dh","Dh","Wk","Wk","Dh","Dh","Dh","Dh","Dh","Dh","Wk","Wk","Wk","Wk","Wk","Wk"},
      side={"L","R"},
      wet="W",
      type={"soil","soilm","rock","clot","grass","grav","wood","iron","tin"},
      soil={symbol="SOILA",wet=true,material={"MTR_SOIL_A","MTR_SOIL_B","MTR_SOIL_F","MTR_SOIL_G","MTR_SOIL_H","MTR_SAND_A","MTR_SAND_B","MTR_PLNT_A"}},
      soilm={symbol="ROCKAW",wet=false,material={"MTR_SOIL_D","MTR_WATE_B","MTR_BLOD_A"}},
      rock={symbol="ROCKA",wet=true,material={"MTR_ROCK_A","MTR_ROCK_B","MTR_BRIC_A","MTR_CONC_A","MTR_CONC_B","MTR_PAPE_A","MTR_RUBB_A","MTR_TILE_A","MTR_VINL_A","MTR_GLAS_A","MTR_RUBB_B","MTR_ROCK_P","MTR_BRIR_A"}},
      clot={symbol="CLOTA",wet=true,material={"MTR_CLOT_C","MTR_CLOT_D"}},
      grass={symbol="GRASA",wet=true,material={"MTR_TURF_A","MTR_LEAF","MTR_TLEF"}},
      grav={symbol="GRAVA",wet=true,material={"MTR_GRAV_A","MTR_SOIL_C"}},
      wood={symbol="WOODA",wet=true,material={"MTR_PAPE_B","MTR_PLAS_A","MTR_PLAS_B","MTR_WOOD_A","MTR_WOOD_B","MTR_WOOD_C","MTR_WOOD_D","MTR_WOOD_W"}},
      iron={symbol="IRONA",wet=true,material={"MTR_IRON_A","MTR_IRON_B","MTR_FENC_A","MTR_FENC_B","MTR_PIPE_A","MTR_PIPE_B","MTR_CLOT_E","MTR_IRON_E","MTR_FENC_F","MTR_IRON_G"}},
      tin={symbol="TIN_A",wet=true,material={"MTR_TIN_A"}}
    }
  end
}
