SoundTppPlayer={
  SetupSwitch2=function()
    SoundPlayerAnimEvent.SetupPlayerType{group="player_type_switch",type={"nom","bony","snk","amr"}}
    SoundPlayerAnimEvent.SetupPlayerRattleWeapon{
      reference={"RATTLE_WEAPON"},
      event="RATTLE_WEAPON",
      group="rattle_weapon_switch",
      action={"wk","wkc","rn","rnc","dh","cr","cp","dh","cp"},type={"none","asult_rifle","hand_gun","sub_machine_gun","sniper_rifle","shot_gun","machine_gun","grenade_launcher","missile","shield"},
      none={symbol="",weaponId={}},
      asult_rifle={symbol="ar00",weaponId={}},
      hand_gun={symbol="",weaponId={}},
      sub_machine_gun={symbol="",weaponId={}},
      sniper_rifle={symbol="sr00",weaponId={}},
      shot_gun={symbol="ar00",weaponId={}},
      machine_gun={symbol="mg01",weaponId={}},
      grenade_launcher={symbol="",weaponId={}},
      missile={symbol="ms00",weaponId={}},
      shield={symbol="sd00",weaponId={}}
    }

    SoundPlayerAnimEvent.SetupPlayerRattleSuit{
      reference={"RATTLE_SUIT"},
      event="sfx_p_rtl_suit_nom_wk",
      group="rattle_suit_switch",
      action={"wk","wkc","rn","rnc","dh","cr","cp","dh","cp"}
    }
    SoundPlayerAnimEvent.SetupPlayerFootStep{
      reference={"FOOT_GROUND_L","FOOT_GROUND_R","FOOT_LEAVE_L","FOOT_LEAVE_R","ARM_GROUND_L","ARM_GROUND_R","ARM_LEAVE_L","ARM_LEAVE_R"},
      events={"FOOT_GROUND_L","FOOT_GROUND_R","FOOT_LEAVE_L","FOOT_LEAVE_R","ARM_GROUND_L","ARM_GROUND_R","ARM_LEAVE_L","ARM_LEAVE_R"},
      group="foot_step_switch",
      action={"Wk","Wk","Wk_Tn","Rn","Rn","Dh","WkC","WkC","WkC_Tn","Rn","Rn","Dh","Rn","Wk","Rn_Tn","Dh","Rn","Dh","RnC","WkC","RnC_Tn","Dh","Rn","Dh","Dh","Wk","Dh_Tn","Dh","Dh","Dh","Rn","El","RnC","El","Cf","Cf","Cr","Cr","Cr","Cr","Cp","Cp","Cp","Cp","Rn_Dv","El","Wk_Be","Wk_Be"},
      wet="W",
      type={"soil","soilw","soilm","rock","clot","grass","grav","wood","iron","fence","tin","ironb","sanda","glasb"},
      soil={symbol="SOILA",wet=true,material={"MTR_SOIL_A","MTR_SOIL_B","MTR_SOIL_E","MTR_SOIL_F","MTR_SOIL_G","MTR_SOIL_H","MTR_SAND_B","MTR_PLNT_A"}},
      soilm={symbol="ROCKAW",wet=false,material={"MTR_SOIL_D","MTR_WATE_B","MTR_BLOD_A"}},
      rock={symbol="ROCKA",wet=true,material={"MTR_ROCK_A","MTR_ROCK_B","MTR_BRIC_A","MTR_CONC_A","MTR_CONC_B","MTR_PAPE_A","MTR_RUBB_A","MTR_TILE_A","MTR_VINL_A","MTR_GLAS_A","MTR_RUBB_B","MTR_ROCK_P","MTR_BRIR_A"}},
      clot={symbol="CLOTA",wet=true,material={"MTR_CLOT_C","MTR_CLOT_D"}},grass={symbol="GRASA",wet=true,material={"MTR_TURF_A","MTR_LEAF","MTR_TLEF"}},grav={symbol="GRAVA",wet=true,material={"MTR_GRAV_A","MTR_SOIL_C"}},
      wood={symbol="WOODA",wet=true,material={"MTR_PAPE_B","MTR_PLAS_A","MTR_PLAS_B","MTR_WOOD_A","MTR_WOOD_B","MTR_WOOD_C","MTR_WOOD_D","MTR_WOOD_W"}},iron={symbol="IRONA",wet=true,material={"MTR_IRON_A","MTR_IRON_B","MTR_IRON_C","MTR_PIPE_A","MTR_PIPE_B","MTR_IRON_E"}},
      fence={symbol="FENCA",wet=true,material={"MTR_FENC_B","MTR_CLOT_E","MTR_FENC_F"}},tin={symbol="TIN_A",wet=true,material={"MTR_TIN_A"}},
      ironb={symbol="IRONB",wet=true,material={"MTR_FENC_A","MTR_IRON_G"}},glasb={symbol="GLASB",wet=true,material={"MTR_GLAS_B","MTR_GLAS_C"}},
      sanda={symbol="SANDA",wet=true,material={"MTR_SAND_A","MTR_WATE_A"}}
    }
  end
}
