local this={}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="MotherBase",grade=1,addCombatLimit=30,addDevelopLimit=30,addBaseDevLimit=30,addSupportLimit=30,addSpyLimit=30,addMedicalLimit=30,addSecurityLimit=25,gmp=0,resourceA="None",resourceACount=0,resourceB="None",resourceBCount=0,timeMinute=0}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="MotherBase",grade=2,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=9e4,resourceA="MinorMetal",resourceACount=1e3,resourceB="FuelResource",resourceBCount=1e3,timeMinute=120}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="MotherBase",grade=3,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=18e4,resourceA="MinorMetal",resourceACount=2e3,resourceB="FuelResource",resourceBCount=4e3,timeMinute=120}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="MotherBase",grade=4,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=24e4,resourceA="MinorMetal",resourceACount=1e4,resourceB="FuelResource",resourceBCount=2e4,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Develop",grade=1,addLimit=10,gmp=4e4,resourceA="CommonMetal",resourceACount=1e3,resourceB="FuelResource",resourceBCount=1e3,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Develop",grade=2,addLimit=15,gmp=12e4,resourceA="CommonMetal",resourceACount=4e3,resourceB="FuelResource",resourceBCount=4e3,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Develop",grade=3,addLimit=15,gmp=24e4,resourceA="CommonMetal",resourceACount=18e3,resourceB="FuelResource",resourceBCount=18e3,timeMinute=180}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Develop",grade=4,addLimit=15,gmp=4e5,resourceA="CommonMetal",resourceACount=48e3,resourceB="FuelResource",resourceBCount=48e3,timeMinute=300}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="BaseDev",grade=1,addLimit=10,gmp=4e4,resourceA="BioticResource",resourceACount=1e3,resourceB="FuelResource",resourceBCount=1e3,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="BaseDev",grade=2,addLimit=15,gmp=12e4,resourceA="BioticResource",resourceACount=4e3,resourceB="FuelResource",resourceBCount=4e3,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="BaseDev",grade=3,addLimit=15,gmp=24e4,resourceA="BioticResource",resourceACount=18e3,resourceB="FuelResource",resourceBCount=18e3,timeMinute=180}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="BaseDev",grade=4,addLimit=15,gmp=4e5,resourceA="BioticResource",resourceACount=48e3,resourceB="FuelResource",resourceBCount=48e3,timeMinute=300}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Support",grade=1,addLimit=10,gmp=4e4,resourceA="CommonMetal",resourceACount=1e3,resourceB="BioticResource",resourceBCount=1e3,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Support",grade=2,addLimit=15,gmp=12e4,resourceA="CommonMetal",resourceACount=4e3,resourceB="BioticResource",resourceBCount=4e3,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Support",grade=3,addLimit=15,gmp=24e4,resourceA="CommonMetal",resourceACount=18e3,resourceB="BioticResource",resourceBCount=18e3,timeMinute=180}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Support",grade=4,addLimit=15,gmp=4e5,resourceA="CommonMetal",resourceACount=48e3,resourceB="BioticResource",resourceBCount=48e3,timeMinute=300}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Spy",grade=1,addLimit=10,gmp=4e4,resourceA="CommonMetal",resourceACount=1e3,resourceB="FuelResource",resourceBCount=1e3,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Spy",grade=2,addLimit=15,gmp=12e4,resourceA="CommonMetal",resourceACount=4e3,resourceB="FuelResource",resourceBCount=4e3,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Spy",grade=3,addLimit=15,gmp=24e4,resourceA="CommonMetal",resourceACount=18e3,resourceB="FuelResource",resourceBCount=18e3,timeMinute=180}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Spy",grade=4,addLimit=15,gmp=4e5,resourceA="CommonMetal",resourceACount=48e3,resourceB="FuelResource",resourceBCount=48e3,timeMinute=300}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Combat",grade=1,addLimit=10,gmp=4e4,resourceA="CommonMetal",resourceACount=1e3,resourceB="FuelResource",resourceBCount=1e3,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Combat",grade=2,addLimit=15,gmp=12e4,resourceA="CommonMetal",resourceACount=4e3,resourceB="FuelResource",resourceBCount=4e3,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Combat",grade=3,addLimit=15,gmp=24e4,resourceA="CommonMetal",resourceACount=18e3,resourceB="FuelResource",resourceBCount=18e3,timeMinute=180}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Combat",grade=4,addLimit=15,gmp=4e5,resourceA="CommonMetal",resourceACount=48e3,resourceB="FuelResource",resourceBCount=48e3,timeMinute=300}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Medical",grade=1,addLimit=10,gmp=4e4,resourceA="BioticResource",resourceACount=1e3,resourceB="FuelResource",resourceBCount=1e3,timeMinute=20}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Medical",grade=2,addLimit=15,gmp=12e4,resourceA="BioticResource",resourceACount=4e3,resourceB="FuelResource",resourceBCount=4e3,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Medical",grade=3,addLimit=15,gmp=24e4,resourceA="BioticResource",resourceACount=18e3,resourceB="FuelResource",resourceBCount=18e3,timeMinute=180}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="MotherBase",category="Medical",grade=4,addLimit=15,gmp=4e5,resourceA="BioticResource",resourceACount=48e3,resourceB="FuelResource",resourceBCount=48e3,timeMinute=300}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob1",grade=1,addCombatLimit=30,addDevelopLimit=30,addBaseDevLimit=30,addSupportLimit=30,addSpyLimit=30,addMedicalLimit=30,addSecurityLimit=25,gmp=4e5,resourceA="None",resourceACount=2e3,resourceB="None",resourceBCount=2e3,timeMinute=0}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob1",grade=2,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=9e5,resourceA="MinorMetal",resourceACount=9e3,resourceB="FuelResource",resourceBCount=9e3,timeMinute=240}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob1",grade=3,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=162e4,resourceA="MinorMetal",resourceACount=24200,resourceB="FuelResource",resourceBCount=24200,timeMinute=420}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob1",grade=4,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=249e4,resourceA="MinorMetal",resourceACount=45600,resourceB="FuelResource",resourceBCount=45600,timeMinute=1380}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Develop",grade=1,addLimit=10,gmp=18e4,resourceA="CommonMetal",resourceACount=5400,resourceB="FuelResource",resourceBCount=5400,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Develop",grade=2,addLimit=15,gmp=2e5,resourceA="CommonMetal",resourceACount=12800,resourceB="FuelResource",resourceBCount=12800,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Develop",grade=3,addLimit=15,gmp=22e4,resourceA="CommonMetal",resourceACount=17e3,resourceB="FuelResource",resourceBCount=17e3,timeMinute=480}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Develop",grade=4,addLimit=15,gmp=72e4,resourceA="CommonMetal",resourceACount=72e3,resourceB="FuelResource",resourceBCount=72e3,timeMinute=960}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="BaseDev",grade=1,addLimit=10,gmp=18e4,resourceA="BioticResource",resourceACount=5400,resourceB="FuelResource",resourceBCount=5400,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="BaseDev",grade=2,addLimit=15,gmp=2e5,resourceA="BioticResource",resourceACount=12800,resourceB="FuelResource",resourceBCount=12800,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="BaseDev",grade=3,addLimit=15,gmp=22e4,resourceA="BioticResource",resourceACount=17e3,resourceB="FuelResource",resourceBCount=17e3,timeMinute=480}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="BaseDev",grade=4,addLimit=15,gmp=72e4,resourceA="BioticResource",resourceACount=72e3,resourceB="FuelResource",resourceBCount=72e3,timeMinute=960}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Support",grade=1,addLimit=10,gmp=18e4,resourceA="CommonMetal",resourceACount=5400,resourceB="BioticResource",resourceBCount=5400,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Support",grade=2,addLimit=15,gmp=2e5,resourceA="CommonMetal",resourceACount=12800,resourceB="BioticResource",resourceBCount=12800,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Support",grade=3,addLimit=15,gmp=22e4,resourceA="CommonMetal",resourceACount=17e3,resourceB="BioticResource",resourceBCount=17e3,timeMinute=480}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Support",grade=4,addLimit=15,gmp=72e4,resourceA="CommonMetal",resourceACount=72e3,resourceB="BioticResource",resourceBCount=72e3,timeMinute=960}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Spy",grade=1,addLimit=10,gmp=18e4,resourceA="CommonMetal",resourceACount=5400,resourceB="FuelResource",resourceBCount=5400,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Spy",grade=2,addLimit=15,gmp=2e5,resourceA="CommonMetal",resourceACount=12800,resourceB="FuelResource",resourceBCount=12800,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Spy",grade=3,addLimit=15,gmp=22e4,resourceA="CommonMetal",resourceACount=17e3,resourceB="FuelResource",resourceBCount=17e3,timeMinute=480}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Spy",grade=4,addLimit=15,gmp=72e4,resourceA="CommonMetal",resourceACount=72e3,resourceB="FuelResource",resourceBCount=72e3,timeMinute=960}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Combat",grade=1,addLimit=10,gmp=18e4,resourceA="CommonMetal",resourceACount=5400,resourceB="FuelResource",resourceBCount=5400,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Combat",grade=2,addLimit=15,gmp=2e5,resourceA="CommonMetal",resourceACount=12800,resourceB="FuelResource",resourceBCount=12800,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Combat",grade=3,addLimit=15,gmp=22e4,resourceA="CommonMetal",resourceACount=17e3,resourceB="FuelResource",resourceBCount=17e3,timeMinute=480}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Combat",grade=4,addLimit=15,gmp=72e4,resourceA="CommonMetal",resourceACount=72e3,resourceB="FuelResource",resourceBCount=72e3,timeMinute=960}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Medical",grade=1,addLimit=10,gmp=18e4,resourceA="BioticResource",resourceACount=5400,resourceB="FuelResource",resourceBCount=5400,timeMinute=60}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Medical",grade=2,addLimit=15,gmp=2e5,resourceA="BioticResource",resourceACount=12800,resourceB="FuelResource",resourceBCount=12800,timeMinute=120}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Medical",grade=3,addLimit=15,gmp=22e4,resourceA="BioticResource",resourceACount=17e3,resourceB="FuelResource",resourceBCount=17e3,timeMinute=480}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob1",category="Medical",grade=4,addLimit=15,gmp=72e4,resourceA="BioticResource",resourceACount=72e3,resourceB="FuelResource",resourceBCount=72e3,timeMinute=960}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob2",grade=1,addCombatLimit=30,addDevelopLimit=30,addBaseDevLimit=30,addSupportLimit=30,addSpyLimit=30,addMedicalLimit=30,addSecurityLimit=25,gmp=25e5,resourceA="None",resourceACount=12500,resourceB="None",resourceBCount=12500,timeMinute=0}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob2",grade=2,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=324e4,resourceA="MinorMetal",resourceACount=36e3,resourceB="FuelResource",resourceBCount=36e3,timeMinute=4320}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob2",grade=3,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=441e4,resourceA="MinorMetal",resourceACount=58800,resourceB="FuelResource",resourceBCount=58800,timeMinute=5760}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob2",grade=4,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=4992e3,resourceA="MinorMetal",resourceACount=102400,resourceB="FuelResource",resourceBCount=102400,timeMinute=7200}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Develop",grade=1,addLimit=10,gmp=72e4,resourceA="CommonMetal",resourceACount=6e3,resourceB="FuelResource",resourceBCount=6e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Develop",grade=2,addLimit=15,gmp=98e4,resourceA="CommonMetal",resourceACount=22400,resourceB="FuelResource",resourceBCount=22400,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Develop",grade=3,addLimit=15,gmp=128e4,resourceA="CommonMetal",resourceACount=64e3,resourceB="FuelResource",resourceBCount=64e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Develop",grade=4,addLimit=15,gmp=162e4,resourceA="CommonMetal",resourceACount=108e3,resourceB="FuelResource",resourceBCount=108e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="BaseDev",grade=1,addLimit=10,gmp=72e4,resourceA="BioticResource",resourceACount=6e3,resourceB="FuelResource",resourceBCount=6e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="BaseDev",grade=2,addLimit=15,gmp=98e4,resourceA="BioticResource",resourceACount=22400,resourceB="FuelResource",resourceBCount=22400,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="BaseDev",grade=3,addLimit=15,gmp=128e4,resourceA="BioticResource",resourceACount=64e3,resourceB="FuelResource",resourceBCount=64e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="BaseDev",grade=4,addLimit=15,gmp=162e4,resourceA="BioticResource",resourceACount=108e3,resourceB="FuelResource",resourceBCount=108e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Support",grade=1,addLimit=10,gmp=72e4,resourceA="CommonMetal",resourceACount=6e3,resourceB="BioticResource",resourceBCount=6e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Support",grade=2,addLimit=15,gmp=98e4,resourceA="CommonMetal",resourceACount=22400,resourceB="BioticResource",resourceBCount=22400,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Support",grade=3,addLimit=15,gmp=128e4,resourceA="CommonMetal",resourceACount=64e3,resourceB="BioticResource",resourceBCount=64e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Support",grade=4,addLimit=15,gmp=162e4,resourceA="CommonMetal",resourceACount=108e3,resourceB="BioticResource",resourceBCount=108e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Spy",grade=1,addLimit=10,gmp=72e4,resourceA="CommonMetal",resourceACount=6e3,resourceB="FuelResource",resourceBCount=6e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Spy",grade=2,addLimit=15,gmp=98e4,resourceA="CommonMetal",resourceACount=22400,resourceB="FuelResource",resourceBCount=22400,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Spy",grade=3,addLimit=15,gmp=128e4,resourceA="CommonMetal",resourceACount=64e3,resourceB="FuelResource",resourceBCount=64e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Spy",grade=4,addLimit=15,gmp=162e4,resourceA="CommonMetal",resourceACount=108e3,resourceB="FuelResource",resourceBCount=108e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Combat",grade=1,addLimit=10,gmp=72e4,resourceA="CommonMetal",resourceACount=6e3,resourceB="FuelResource",resourceBCount=6e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Combat",grade=2,addLimit=15,gmp=98e4,resourceA="CommonMetal",resourceACount=22400,resourceB="FuelResource",resourceBCount=22400,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Combat",grade=3,addLimit=15,gmp=128e4,resourceA="CommonMetal",resourceACount=64e3,resourceB="FuelResource",resourceBCount=64e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Combat",grade=4,addLimit=15,gmp=162e4,resourceA="CommonMetal",resourceACount=108e3,resourceB="FuelResource",resourceBCount=108e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Medical",grade=1,addLimit=10,gmp=72e4,resourceA="BioticResource",resourceACount=6e3,resourceB="FuelResource",resourceBCount=6e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Medical",grade=2,addLimit=15,gmp=98e4,resourceA="BioticResource",resourceACount=22400,resourceB="FuelResource",resourceBCount=22400,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Medical",grade=3,addLimit=15,gmp=128e4,resourceA="BioticResource",resourceACount=64e3,resourceB="FuelResource",resourceBCount=64e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob2",category="Medical",grade=4,addLimit=15,gmp=162e4,resourceA="BioticResource",resourceACount=108e3,resourceB="FuelResource",resourceBCount=108e3,timeMinute=5760}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob3",grade=1,addCombatLimit=30,addDevelopLimit=30,addBaseDevLimit=30,addSupportLimit=30,addSpyLimit=30,addMedicalLimit=30,addSecurityLimit=25,gmp=81e5,resourceA="None",resourceACount=40500,resourceB="None",resourceBCount=40500,timeMinute=0}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob3",grade=2,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=9e6,resourceA="MinorMetal",resourceACount=1e5,resourceB="FuelResource",resourceBCount=1e5,timeMinute=4320}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob3",grade=3,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=1089e4,resourceA="MinorMetal",resourceACount=145200,resourceB="FuelResource",resourceBCount=145200,timeMinute=5760}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob3",grade=4,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=1296e4,resourceA="MinorMetal",resourceACount=230400,resourceB="FuelResource",resourceBCount=230400,timeMinute=7200}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Develop",grade=1,addLimit=10,gmp=162e4,resourceA="CommonMetal",resourceACount=9e3,resourceB="FuelResource",resourceBCount=9e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Develop",grade=2,addLimit=15,gmp=2e6,resourceA="CommonMetal",resourceACount=32e3,resourceB="FuelResource",resourceBCount=32e3,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Develop",grade=3,addLimit=15,gmp=242e4,resourceA="CommonMetal",resourceACount=88e3,resourceB="FuelResource",resourceBCount=88e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Develop",grade=4,addLimit=15,gmp=288e4,resourceA="CommonMetal",resourceACount=144e3,resourceB="FuelResource",resourceBCount=144e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="BaseDev",grade=1,addLimit=10,gmp=162e4,resourceA="BioticResource",resourceACount=9e3,resourceB="FuelResource",resourceBCount=9e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="BaseDev",grade=2,addLimit=15,gmp=2e6,resourceA="BioticResource",resourceACount=32e3,resourceB="FuelResource",resourceBCount=32e3,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="BaseDev",grade=3,addLimit=15,gmp=242e4,resourceA="BioticResource",resourceACount=88e3,resourceB="FuelResource",resourceBCount=88e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="BaseDev",grade=4,addLimit=15,gmp=288e4,resourceA="BioticResource",resourceACount=144e3,resourceB="FuelResource",resourceBCount=144e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Support",grade=1,addLimit=10,gmp=162e4,resourceA="CommonMetal",resourceACount=9e3,resourceB="BioticResource",resourceBCount=9e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Support",grade=2,addLimit=15,gmp=2e6,resourceA="CommonMetal",resourceACount=32e3,resourceB="BioticResource",resourceBCount=32e3,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Support",grade=3,addLimit=15,gmp=242e4,resourceA="CommonMetal",resourceACount=88e3,resourceB="BioticResource",resourceBCount=88e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Support",grade=4,addLimit=15,gmp=288e4,resourceA="CommonMetal",resourceACount=144e3,resourceB="BioticResource",resourceBCount=144e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Spy",grade=1,addLimit=10,gmp=162e4,resourceA="CommonMetal",resourceACount=9e3,resourceB="FuelResource",resourceBCount=9e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Spy",grade=2,addLimit=15,gmp=2e6,resourceA="CommonMetal",resourceACount=32e3,resourceB="FuelResource",resourceBCount=32e3,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Spy",grade=3,addLimit=15,gmp=242e4,resourceA="CommonMetal",resourceACount=88e3,resourceB="FuelResource",resourceBCount=88e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Spy",grade=4,addLimit=15,gmp=288e4,resourceA="CommonMetal",resourceACount=144e3,resourceB="FuelResource",resourceBCount=144e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Combat",grade=1,addLimit=10,gmp=162e4,resourceA="CommonMetal",resourceACount=9e3,resourceB="FuelResource",resourceBCount=9e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Combat",grade=2,addLimit=15,gmp=2e6,resourceA="CommonMetal",resourceACount=32e3,resourceB="FuelResource",resourceBCount=32e3,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Combat",grade=3,addLimit=15,gmp=242e4,resourceA="CommonMetal",resourceACount=88e3,resourceB="FuelResource",resourceBCount=88e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Combat",grade=4,addLimit=15,gmp=288e4,resourceA="CommonMetal",resourceACount=144e3,resourceB="FuelResource",resourceBCount=144e3,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Medical",grade=1,addLimit=10,gmp=162e4,resourceA="BioticResource",resourceACount=9e3,resourceB="FuelResource",resourceBCount=9e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Medical",grade=2,addLimit=15,gmp=2e6,resourceA="BioticResource",resourceACount=32e3,resourceB="FuelResource",resourceBCount=32e3,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Medical",grade=3,addLimit=15,gmp=242e4,resourceA="BioticResource",resourceACount=88e3,resourceB="FuelResource",resourceBCount=88e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob3",category="Medical",grade=4,addLimit=15,gmp=288e4,resourceA="BioticResource",resourceACount=144e3,resourceB="FuelResource",resourceBCount=144e3,timeMinute=5760}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob4",grade=1,addCombatLimit=30,addDevelopLimit=30,addBaseDevLimit=30,addSupportLimit=30,addSpyLimit=30,addMedicalLimit=30,addSecurityLimit=25,gmp=196e5,resourceA="None",resourceACount=98e3,resourceB="None",resourceBCount=98e3,timeMinute=0}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob4",grade=2,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=2025e4,resourceA="MinorMetal",resourceACount=225e3,resourceB="FuelResource",resourceBCount=225e3,timeMinute=4320}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob4",grade=3,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=2304e4,resourceA="MinorMetal",resourceACount=307200,resourceB="FuelResource",resourceBCount=307200,timeMinute=5760}
TppMotherBaseManagement.RegisterCommandClusterBuildParam{base="Fob4",grade=4,addCombatLimit=5,addDevelopLimit=5,addBaseDevLimit=5,addSupportLimit=5,addSpyLimit=5,addMedicalLimit=5,addSecurityLimit=25,gmp=2601e4,resourceA="MinorMetal",resourceACount=462400,resourceB="FuelResource",resourceBCount=462400,timeMinute=7200}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Develop",grade=1,addLimit=10,gmp=288e4,resourceA="CommonMetal",resourceACount=12e3,resourceB="FuelResource",resourceBCount=12e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Develop",grade=2,addLimit=15,gmp=338e4,resourceA="CommonMetal",resourceACount=41600,resourceB="FuelResource",resourceBCount=41600,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Develop",grade=3,addLimit=15,gmp=392e4,resourceA="CommonMetal",resourceACount=112e3,resourceB="FuelResource",resourceBCount=112e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Develop",grade=4,addLimit=15,gmp=45e5,resourceA="CommonMetal",resourceACount=18e4,resourceB="FuelResource",resourceBCount=18e4,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="BaseDev",grade=1,addLimit=10,gmp=288e4,resourceA="BioticResource",resourceACount=12e3,resourceB="FuelResource",resourceBCount=12e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="BaseDev",grade=2,addLimit=15,gmp=338e4,resourceA="BioticResource",resourceACount=41600,resourceB="FuelResource",resourceBCount=41600,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="BaseDev",grade=3,addLimit=15,gmp=392e4,resourceA="BioticResource",resourceACount=112e3,resourceB="FuelResource",resourceBCount=112e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="BaseDev",grade=4,addLimit=15,gmp=45e5,resourceA="BioticResource",resourceACount=18e4,resourceB="FuelResource",resourceBCount=18e4,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Support",grade=1,addLimit=10,gmp=288e4,resourceA="CommonMetal",resourceACount=12e3,resourceB="BioticResource",resourceBCount=12e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Support",grade=2,addLimit=15,gmp=338e4,resourceA="CommonMetal",resourceACount=41600,resourceB="BioticResource",resourceBCount=41600,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Support",grade=3,addLimit=15,gmp=392e4,resourceA="CommonMetal",resourceACount=112e3,resourceB="BioticResource",resourceBCount=112e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Support",grade=4,addLimit=15,gmp=45e5,resourceA="CommonMetal",resourceACount=18e4,resourceB="BioticResource",resourceBCount=18e4,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Spy",grade=1,addLimit=10,gmp=288e4,resourceA="CommonMetal",resourceACount=12e3,resourceB="FuelResource",resourceBCount=12e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Spy",grade=2,addLimit=15,gmp=338e4,resourceA="CommonMetal",resourceACount=41600,resourceB="FuelResource",resourceBCount=41600,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Spy",grade=3,addLimit=15,gmp=392e4,resourceA="CommonMetal",resourceACount=112e3,resourceB="FuelResource",resourceBCount=112e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Spy",grade=4,addLimit=15,gmp=45e5,resourceA="CommonMetal",resourceACount=18e4,resourceB="FuelResource",resourceBCount=18e4,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Combat",grade=1,addLimit=10,gmp=288e4,resourceA="CommonMetal",resourceACount=12e3,resourceB="FuelResource",resourceBCount=12e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Combat",grade=2,addLimit=15,gmp=338e4,resourceA="CommonMetal",resourceACount=41600,resourceB="FuelResource",resourceBCount=41600,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Combat",grade=3,addLimit=15,gmp=392e4,resourceA="CommonMetal",resourceACount=112e3,resourceB="FuelResource",resourceBCount=112e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Combat",grade=4,addLimit=15,gmp=45e5,resourceA="CommonMetal",resourceACount=18e4,resourceB="FuelResource",resourceBCount=18e4,timeMinute=5760}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Medical",grade=1,addLimit=10,gmp=288e4,resourceA="BioticResource",resourceACount=12e3,resourceB="FuelResource",resourceBCount=12e3,timeMinute=360}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Medical",grade=2,addLimit=15,gmp=338e4,resourceA="BioticResource",resourceACount=41600,resourceB="FuelResource",resourceBCount=41600,timeMinute=720}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Medical",grade=3,addLimit=15,gmp=392e4,resourceA="BioticResource",resourceACount=112e3,resourceB="FuelResource",resourceBCount=112e3,timeMinute=4320}
TppMotherBaseManagement.RegisterSectionClusterBuildParam{base="Fob4",category="Medical",grade=4,addLimit=15,gmp=45e5,resourceA="BioticResource",resourceACount=18e4,resourceB="FuelResource",resourceBCount=18e4,timeMinute=5760}
TppMotherBaseManagement.SetSmallDiamondGmp{gmp=TppDefine.SMALL_DIAMOND_GMP}
TppMotherBaseManagement.SetLargeDiamondGmp{gmp=TppDefine.LARGE_DIAMOND_GMP}
TppMotherBaseManagement.RegisterResourceBaseExtractingTimeMinute{timeMinute=1}
TppMotherBaseManagement.RegisterContainerParam{
  commonMetalCounts={white=750,red=7500,yellow=1500},
  fuelResourceCounts={white=750,red=7500,yellow=1500},
  bioticResourceCounts={white=750,red=7500,yellow=1500},
  minorMetalCounts={white=400,red=4e3,yellow=800},
  preciousMetalCounts={white=50,red=500,yellow=100},
  usableResourceContainerRate=50,
  redContainerCountRate=40,
  yellowContainerCountRate=40
}
TppMotherBaseManagement.RegisterResourceParam{resource="CommonMetal",baseSalePrice=100,countInContainer=50,countPer1Minute=4}
TppMotherBaseManagement.RegisterResourceParam{resource="FuelResource",baseSalePrice=100,countInContainer=50,countPer1Minute=4}
TppMotherBaseManagement.RegisterResourceParam{resource="BioticResource",baseSalePrice=100,countInContainer=50,countPer1Minute=4}
TppMotherBaseManagement.RegisterResourceParam{resource="MinorMetal",baseSalePrice=200,countInContainer=50,countPer1Minute=4}
TppMotherBaseManagement.RegisterResourceParam{resource="PreciousMetal",baseSalePrice=1e3,countInContainer=50,countPer1Minute=4}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2000",baseSalePrice=500}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2005",baseSalePrice=500}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2001",baseSalePrice=1e3}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2004",baseSalePrice=1e3}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2006",baseSalePrice=1e3}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2002",baseSalePrice=1e3}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2003",baseSalePrice=5e3}
TppMotherBaseManagement.RegisterResourceParam{resource="Plant2007",baseSalePrice=5e3}
TppMotherBaseManagement.RegisterResourceParam{resource="4wdEast",baseSalePrice=2e4}
TppMotherBaseManagement.RegisterResourceParam{resource="4wdWest",baseSalePrice=2e4}
TppMotherBaseManagement.RegisterResourceParam{resource="TruckEast",baseSalePrice=3e4}
TppMotherBaseManagement.RegisterResourceParam{resource="TruckWest",baseSalePrice=3e4}
TppMotherBaseManagement.RegisterResourceParam{resource="ArmoredVehicleEast",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="ArmoredVehicleWest",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="ArmoredVehicleEastRocket",baseSalePrice=7e4}
TppMotherBaseManagement.RegisterResourceParam{resource="WheeledArmoredVehicleWest",baseSalePrice=7e4}
TppMotherBaseManagement.RegisterResourceParam{resource="TankEast",baseSalePrice=1e5}
TppMotherBaseManagement.RegisterResourceParam{resource="TankWest",baseSalePrice=1e5}
TppMotherBaseManagement.RegisterResourceParam{resource="SovietWalkerGear1",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="SovietWalkerGear2",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="SovietWalkerGear3",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="CfaWalkerGear1",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="CfaWalkerGear2",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="CfaWalkerGear3",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="RogueCoyoteWalkerGear1",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="RogueCoyoteWalkerGear2",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="RogueCoyoteWalkerGear3",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="ZrsWalkerGear1",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="ZrsWalkerGear2",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="ZrsWalkerGear3",baseSalePrice=5e4}
TppMotherBaseManagement.RegisterResourceParam{resource="NuclearWeapon",baseSalePrice=75e4}
TppMotherBaseManagement.RegisterResourceParam{resource="NuclearWaste",baseSalePrice=1e5}
TppMotherBaseManagement.RegisterResourceParam{resource="ParasiteFog",baseSalePrice=10}
TppMotherBaseManagement.RegisterResourceParam{resource="ParasiteCamofla",baseSalePrice=10}
TppMotherBaseManagement.RegisterResourceParam{resource="ParasiteCuring",baseSalePrice=10}
TppMotherBaseManagement.RegisterResourceParam{resource="EmplacementGunEast",baseSalePrice=12e3}
TppMotherBaseManagement.RegisterResourceParam{resource="EmplacementGunWest",baseSalePrice=12e3}
TppMotherBaseManagement.RegisterResourceParam{resource="Mortar",baseSalePrice=9e3}
TppMotherBaseManagement.RegisterResourceParam{resource="AntiAirGatlingGunEast",baseSalePrice=2e4}
TppMotherBaseManagement.RegisterResourceParam{resource="AntiAirGatlingGunWest",baseSalePrice=2e4}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="commFacility_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="commFacility_cntn002",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn002",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn003",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn004",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn005",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn006",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn007",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="enemyBase_cntn008",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="remnants_cntn001",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="remnants_cntn002",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="remnants_cntn003",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="tent_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="tent_cntn002",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bridge_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bridge_cntn002",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bridge_cntn003",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bridge_cntn004",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bridge_cntn005",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bridge_cntn006",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bridge_cntn007",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn002",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn003",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn004",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn005",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn006",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn007",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn008",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn009",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn010",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn011",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn012",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="sovietBase_cntn013",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn001",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn002",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn003",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn004",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn005",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn006",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn007",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn008",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn009",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn010",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadel_cntn011",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadelSouth_cntn001",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadelSouth_cntn002",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="citadelSouth_cntn003",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="outland_cntn001",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="flowStation_cntn001",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="flowStation_cntn002",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="flowStation_cntn003",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="flowStation_cntn004",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="flowStation_cntn005",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="flowStation_cntn006",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="swamp_cntn001",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="swamp_cntn002",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="swamp_cntn003",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="swamp_cntn004",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn001",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn015",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn004",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn005",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn006",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn007",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn002",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn003",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn008",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn009",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn010",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn011",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn012",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn013",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="pfCamp_cntn014",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="chicoVilWest_cntn001",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="chicoVilWest_cntn002",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamond_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamond_cntn002",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamond_cntn003",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamond_cntn004",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamond_cntn005",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamond_cntn006",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamondWest_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamondWest_cntn002",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamondWest_cntn003",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamondWest_cntn004",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamondWest_cntn005",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamondSouth_cntn001",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="diamondSouth_cntn002",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bananaSouth_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="bananaSouth_cntn002",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hill_cntn001",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hill_cntn002",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hill_cntn003",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hill_cntn004",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hill_cntn005",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillNorth_cntn001",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillNorth_cntn002",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillNorth_cntn003",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillNorth_cntn004",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillWest_cntn001",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillWest_cntn002",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillWest_cntn003",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillWest_cntn004",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillSouth_cntn001",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="hillSouth_cntn002",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="factorySouth_cntn001",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="factorySouth_cntn002",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="savannahEast_cntn001",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_WHITE}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="savannahEast_cntn002",resource="BioticResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="powerPlant_cntn001",resource="MinorMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="powerPlant_cntn002",resource="FuelResource",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="powerPlant_cntn003",resource="PreciousMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterStageGimmickParam{gimmickName="powerPlant_cntn004",resource="CommonMetal",containerVisual=TppMotherBaseManagementConst.CONTAINER_VISUAL_RED}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_COMBAT_DEPLOY,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_COMBAT_DEFENCE,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_WEAPON,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_ITEM,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_HELI,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_QUIET,bLv=1,aLv=25,sLv=41}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_D_DOG,bLv=1,aLv=14,sLv=25}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_D_HORSE,bLv=1,aLv=14,sLv=25}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_D_WALKER,eLv=1,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_BATTLE_GEAR,dLv=1,cLv=14,bLv=25,aLv=41,sLv=61}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_DEVELOP_SECURITY_DEVICE,fLv=1,cLv=1,bLv=25,aLv=41,sLv=61}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_BASE_DEV_RESOURCE_MINING,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_BASE_DEV_RESOURCE_PROCESSING,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_BASE_DEV_PLATFORM_EXTENTION,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_BASE_DEV_FOB_CONSTRUCT,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_BASE_DEV_NUCLEAR_DEVELOP,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_FULTON,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_SUPPLY,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_BATTLE,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_STRIKE,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_SMOKE,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_SLEEP_GAS,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_CHAFF,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_WEATHER,sLv=33}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_RUSSIAN_TRANSLATE,sLv=1}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_PASHTO_TRANSLATE,sLv=1}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_AFRIKAANS_TRANSLATE,sLv=1}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SUPPORT_KIKONGO_TRANSLATE,sLv=1}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SPY_MISSION_INFO_COLLECTING,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SPY_ENEMY_SEARCH,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SPY_RESOURCE_SEARCH,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SPY_WEATHER_INFO,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SPY_SECURITY_INFO,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_MEDICAL_STAFF_EMERGENCY,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_MEDICAL_STAFF_TREATMENT,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_MEDICAL_ANTI_REFLEX,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SECURITY_BASE_DEFENCE_STAFF,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SECURITY_BASE_DEFENCE_MACHINE,fLv=1,eLv=5,dLv=14,cLv=25,bLv=41,aLv=61,sLv=85}
TppMotherBaseManagement.RegisterSectionFuncRankLines{sectionFuncId=TppMotherBaseManagementConst.SECTION_FUNC_ID_SECURITY_BASE_BLOCKADE,fLv=1,eLv=9,dLv=19,cLv=33,bLv=51,aLv=73,sLv=99}
TppMotherBaseManagement.RegisterCombatSectionFuncAutoGmp{f=2e4,e=3e4,d=4e4,c=5e4,b=6e4,a=7e4,s=8e4}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=1,sectionFuncRank="F",count=6e3,commonMetalRate=33,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=1,sectionFuncRank="E",count=6500,commonMetalRate=31,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=31,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=1,sectionFuncRank="D",count=7e3,commonMetalRate=29,minorMetalRate=10,preciousMetalRate=2,fuelResourceRate=30,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=1,sectionFuncRank="C",count=7500,commonMetalRate=28,minorMetalRate=13,preciousMetalRate=3,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=1,sectionFuncRank="B",count=8500,commonMetalRate=26,minorMetalRate=18,preciousMetalRate=3,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=1,sectionFuncRank="A",count=9e3,commonMetalRate=26,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=1,sectionFuncRank="S",count=1e4,commonMetalRate=25,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=24,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=11,sectionFuncRank="F",count=1080,commonMetalRate=30,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=30,bioticResourceRate=30}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=11,sectionFuncRank="E",count=1170,commonMetalRate=28,minorMetalRate=7,preciousMetalRate=1,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=11,sectionFuncRank="D",count=1260,commonMetalRate=26,minorMetalRate=11,preciousMetalRate=2,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=11,sectionFuncRank="C",count=1350,commonMetalRate=25,minorMetalRate=14,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=11,sectionFuncRank="B",count=1530,commonMetalRate=23,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=24,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=11,sectionFuncRank="A",count=1620,commonMetalRate=23,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=23,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=11,sectionFuncRank="S",count=1800,commonMetalRate=23,minorMetalRate=24,preciousMetalRate=6,fuelResourceRate=22,bioticResourceRate=22}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=10,sectionFuncRank="F",count=1200,commonMetalRate=30,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=30,bioticResourceRate=30}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=10,sectionFuncRank="E",count=1300,commonMetalRate=28,minorMetalRate=7,preciousMetalRate=1,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=10,sectionFuncRank="D",count=1400,commonMetalRate=26,minorMetalRate=11,preciousMetalRate=2,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=10,sectionFuncRank="C",count=1500,commonMetalRate=25,minorMetalRate=14,preciousMetalRate=3,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=10,sectionFuncRank="B",count=1700,commonMetalRate=23,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=24,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=10,sectionFuncRank="A",count=1800,commonMetalRate=23,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=23,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=10,sectionFuncRank="S",count=2e3,commonMetalRate=23,minorMetalRate=24,preciousMetalRate=6,fuelResourceRate=22,bioticResourceRate=22}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=21,sectionFuncRank="F",count=1020,commonMetalRate=30,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=30,bioticResourceRate=30}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=21,sectionFuncRank="E",count=1105,commonMetalRate=28,minorMetalRate=7,preciousMetalRate=1,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=21,sectionFuncRank="D",count=1190,commonMetalRate=26,minorMetalRate=12,preciousMetalRate=2,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=21,sectionFuncRank="C",count=1275,commonMetalRate=25,minorMetalRate=16,preciousMetalRate=3,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=21,sectionFuncRank="B",count=1445,commonMetalRate=23,minorMetalRate=22,preciousMetalRate=3,fuelResourceRate=24,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=21,sectionFuncRank="A",count=1530,commonMetalRate=23,minorMetalRate=24,preciousMetalRate=4,fuelResourceRate=23,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=21,sectionFuncRank="S",count=1700,commonMetalRate=23,minorMetalRate=26,preciousMetalRate=6,fuelResourceRate=22,bioticResourceRate=22}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=20,sectionFuncRank="F",count=1080,commonMetalRate=30,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=30,bioticResourceRate=30}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=20,sectionFuncRank="E",count=1170,commonMetalRate=28,minorMetalRate=7,preciousMetalRate=1,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=20,sectionFuncRank="D",count=1260,commonMetalRate=26,minorMetalRate=12,preciousMetalRate=2,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=20,sectionFuncRank="C",count=1350,commonMetalRate=25,minorMetalRate=16,preciousMetalRate=3,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=20,sectionFuncRank="B",count=1530,commonMetalRate=23,minorMetalRate=22,preciousMetalRate=3,fuelResourceRate=24,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=20,sectionFuncRank="A",count=1620,commonMetalRate=23,minorMetalRate=24,preciousMetalRate=4,fuelResourceRate=23,bioticResourceRate=23}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=20,sectionFuncRank="S",count=1800,commonMetalRate=23,minorMetalRate=26,preciousMetalRate=6,fuelResourceRate=22,bioticResourceRate=22}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=31,sectionFuncRank="F",count=960,commonMetalRate=33,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=31,sectionFuncRank="E",count=1040,commonMetalRate=31,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=31,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=31,sectionFuncRank="D",count=1120,commonMetalRate=29,minorMetalRate=11,preciousMetalRate=2,fuelResourceRate=30,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=31,sectionFuncRank="C",count=1200,commonMetalRate=28,minorMetalRate=14,preciousMetalRate=3,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=31,sectionFuncRank="B",count=1360,commonMetalRate=26,minorMetalRate=19,preciousMetalRate=3,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=31,sectionFuncRank="A",count=1440,commonMetalRate=26,minorMetalRate=21,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=31,sectionFuncRank="S",count=1600,commonMetalRate=25,minorMetalRate=23,preciousMetalRate=5,fuelResourceRate=24,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=30,sectionFuncRank="F",count=1050,commonMetalRate=33,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=30,sectionFuncRank="E",count=1138,commonMetalRate=31,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=31,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=30,sectionFuncRank="D",count=1225,commonMetalRate=29,minorMetalRate=11,preciousMetalRate=2,fuelResourceRate=30,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=30,sectionFuncRank="C",count=1313,commonMetalRate=28,minorMetalRate=14,preciousMetalRate=3,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=30,sectionFuncRank="B",count=1488,commonMetalRate=26,minorMetalRate=19,preciousMetalRate=3,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=30,sectionFuncRank="A",count=1575,commonMetalRate=26,minorMetalRate=21,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=30,sectionFuncRank="S",count=1750,commonMetalRate=25,minorMetalRate=23,preciousMetalRate=5,fuelResourceRate=24,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=41,sectionFuncRank="F",count=960,commonMetalRate=33,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=41,sectionFuncRank="E",count=1040,commonMetalRate=31,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=31,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=41,sectionFuncRank="D",count=1120,commonMetalRate=29,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=30,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=41,sectionFuncRank="C",count=1200,commonMetalRate=28,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=41,sectionFuncRank="B",count=1360,commonMetalRate=26,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=41,sectionFuncRank="A",count=1440,commonMetalRate=26,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=41,sectionFuncRank="S",count=1600,commonMetalRate=25,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=24,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=40,sectionFuncRank="F",count=1050,commonMetalRate=33,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=40,sectionFuncRank="E",count=1138,commonMetalRate=31,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=31,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=40,sectionFuncRank="D",count=1225,commonMetalRate=29,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=30,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=40,sectionFuncRank="C",count=1313,commonMetalRate=28,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=40,sectionFuncRank="B",count=1488,commonMetalRate=26,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=40,sectionFuncRank="A",count=1575,commonMetalRate=26,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=40,sectionFuncRank="S",count=1750,commonMetalRate=25,minorMetalRate=0,preciousMetalRate=0,fuelResourceRate=24,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=51,sectionFuncRank="F",count=900,commonMetalRate=50,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=51,sectionFuncRank="E",count=975,commonMetalRate=47,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=31,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=51,sectionFuncRank="D",count=1050,commonMetalRate=44,minorMetalRate=10,preciousMetalRate=2,fuelResourceRate=30,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=51,sectionFuncRank="C",count=1125,commonMetalRate=42,minorMetalRate=13,preciousMetalRate=3,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=51,sectionFuncRank="B",count=1275,commonMetalRate=39,minorMetalRate=18,preciousMetalRate=3,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=51,sectionFuncRank="A",count=1350,commonMetalRate=39,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=51,sectionFuncRank="S",count=1500,commonMetalRate=38,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=24,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=50,sectionFuncRank="F",count=1020,commonMetalRate=50,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=50,sectionFuncRank="E",count=1105,commonMetalRate=47,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=31,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=50,sectionFuncRank="D",count=1190,commonMetalRate=44,minorMetalRate=10,preciousMetalRate=2,fuelResourceRate=30,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=50,sectionFuncRank="C",count=1275,commonMetalRate=42,minorMetalRate=13,preciousMetalRate=3,fuelResourceRate=28,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=50,sectionFuncRank="B",count=1445,commonMetalRate=39,minorMetalRate=18,preciousMetalRate=3,fuelResourceRate=27,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=50,sectionFuncRank="A",count=1530,commonMetalRate=39,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=50,sectionFuncRank="S",count=1700,commonMetalRate=38,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=24,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=61,sectionFuncRank="F",count=900,commonMetalRate=33,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=50}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=61,sectionFuncRank="E",count=975,commonMetalRate=31,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=31,bioticResourceRate=47}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=61,sectionFuncRank="D",count=1050,commonMetalRate=29,minorMetalRate=10,preciousMetalRate=2,fuelResourceRate=30,bioticResourceRate=44}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=61,sectionFuncRank="C",count=1125,commonMetalRate=28,minorMetalRate=13,preciousMetalRate=3,fuelResourceRate=28,bioticResourceRate=42}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=61,sectionFuncRank="B",count=1275,commonMetalRate=26,minorMetalRate=18,preciousMetalRate=3,fuelResourceRate=27,bioticResourceRate=39}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=61,sectionFuncRank="A",count=1350,commonMetalRate=26,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=38}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=61,sectionFuncRank="S",count=1500,commonMetalRate=25,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=24,bioticResourceRate=36}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=60,sectionFuncRank="F",count=1020,commonMetalRate=33,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=33,bioticResourceRate=50}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=60,sectionFuncRank="E",count=1105,commonMetalRate=31,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=31,bioticResourceRate=47}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=60,sectionFuncRank="D",count=1190,commonMetalRate=29,minorMetalRate=10,preciousMetalRate=2,fuelResourceRate=30,bioticResourceRate=44}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=60,sectionFuncRank="C",count=1275,commonMetalRate=28,minorMetalRate=13,preciousMetalRate=3,fuelResourceRate=28,bioticResourceRate=42}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=60,sectionFuncRank="B",count=1445,commonMetalRate=26,minorMetalRate=18,preciousMetalRate=3,fuelResourceRate=27,bioticResourceRate=39}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=60,sectionFuncRank="A",count=1530,commonMetalRate=26,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=25,bioticResourceRate=38}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=60,sectionFuncRank="S",count=1700,commonMetalRate=25,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=24,bioticResourceRate=36}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=71,sectionFuncRank="F",count=900,commonMetalRate=33,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=50,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=71,sectionFuncRank="E",count=975,commonMetalRate=31,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=47,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=71,sectionFuncRank="D",count=1050,commonMetalRate=29,minorMetalRate=10,preciousMetalRate=2,fuelResourceRate=45,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=71,sectionFuncRank="C",count=1125,commonMetalRate=28,minorMetalRate=13,preciousMetalRate=3,fuelResourceRate=42,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=71,sectionFuncRank="B",count=1275,commonMetalRate=26,minorMetalRate=18,preciousMetalRate=3,fuelResourceRate=41,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=71,sectionFuncRank="A",count=1350,commonMetalRate=26,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=38,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=71,sectionFuncRank="S",count=1500,commonMetalRate=25,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=36,bioticResourceRate=24}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=70,sectionFuncRank="F",count=1020,commonMetalRate=33,minorMetalRate=1,preciousMetalRate=0,fuelResourceRate=50,bioticResourceRate=33}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=70,sectionFuncRank="E",count=1105,commonMetalRate=31,minorMetalRate=6,preciousMetalRate=1,fuelResourceRate=47,bioticResourceRate=31}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=70,sectionFuncRank="D",count=1190,commonMetalRate=29,minorMetalRate=10,preciousMetalRate=2,fuelResourceRate=45,bioticResourceRate=29}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=70,sectionFuncRank="C",count=1275,commonMetalRate=28,minorMetalRate=13,preciousMetalRate=3,fuelResourceRate=42,bioticResourceRate=28}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=70,sectionFuncRank="B",count=1445,commonMetalRate=26,minorMetalRate=18,preciousMetalRate=3,fuelResourceRate=41,bioticResourceRate=26}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=70,sectionFuncRank="A",count=1530,commonMetalRate=26,minorMetalRate=20,preciousMetalRate=4,fuelResourceRate=38,bioticResourceRate=25}
TppMotherBaseManagement.RegisterAutoResourceParam{oceanAreaId=70,sectionFuncRank="S",count=1700,commonMetalRate=25,minorMetalRate=22,preciousMetalRate=5,fuelResourceRate=36,bioticResourceRate=24}
TppMotherBaseManagement.RegisterContainerProcessingParam{sectionFuncRank="F",commonMetalTimeMinute=60,minorMetalTimeMinute=60,preciousMetalTimeMinute=60,fuelResourceTimeMinute=60,bioticResourceTimeMinute=60}
TppMotherBaseManagement.RegisterContainerProcessingParam{sectionFuncRank="E",commonMetalTimeMinute=48,minorMetalTimeMinute=48,preciousMetalTimeMinute=48,fuelResourceTimeMinute=48,bioticResourceTimeMinute=48}
TppMotherBaseManagement.RegisterContainerProcessingParam{sectionFuncRank="D",commonMetalTimeMinute=36,minorMetalTimeMinute=36,preciousMetalTimeMinute=36,fuelResourceTimeMinute=36,bioticResourceTimeMinute=36}
TppMotherBaseManagement.RegisterContainerProcessingParam{sectionFuncRank="C",commonMetalTimeMinute=25,minorMetalTimeMinute=25,preciousMetalTimeMinute=25,fuelResourceTimeMinute=25,bioticResourceTimeMinute=25}
TppMotherBaseManagement.RegisterContainerProcessingParam{sectionFuncRank="B",commonMetalTimeMinute=15,minorMetalTimeMinute=15,preciousMetalTimeMinute=15,fuelResourceTimeMinute=15,bioticResourceTimeMinute=15}
TppMotherBaseManagement.RegisterContainerProcessingParam{sectionFuncRank="A",commonMetalTimeMinute=12,minorMetalTimeMinute=12,preciousMetalTimeMinute=12,fuelResourceTimeMinute=12,bioticResourceTimeMinute=12}
TppMotherBaseManagement.RegisterContainerProcessingParam{sectionFuncRank="S",commonMetalTimeMinute=10,minorMetalTimeMinute=10,preciousMetalTimeMinute=10,fuelResourceTimeMinute=10,bioticResourceTimeMinute=10}
TppMotherBaseManagement.RegisterContainerProcessingBasicParam{commonMetalProcessCount=500,minorMetalProcessCount=250,preciousMetalProcessCount=50,fuelResourceProcessCount=500,bioticResourceProcessCount=500,fobRate=.15}
TppMotherBaseManagement.RegisterMedicalSectionFuncTreatmentParam{treatmentTimeMinute=12,treatmentRates={none=0,f=50,e=55,d=60,c=70,b=80,a=90,s=100},worseRate=50,deadRates={weight1=1,weight2=2,weight3=3,weight4=4,weight5=5,weight6=10,weight7=20},deadCountLimit=5,initWeightMildMin=1,initWeightMildMax=2,initWeightStandardMin=2,initWeightStandardMax=4,initWeightCriticalMin=3,initWeightCriticalMax=5,sickRateWithRed=5,sickCountLimitWithRed=3}
TppMotherBaseManagement.RegisterBaseDevSectionFuncPlatformExtentionParam{f=100,e=90,d=80,c=70,b=60,a=55,s=50}
return this
